name: OSX
on: [push]

jobs:
  build:
    runs-on: macOS-latest
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install dependencies
        run: brew install cmake
      - name: configure project
        run: cmake -H. -B "${{ env.CMAKE_BUILD_DIR }}" -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
      - name: build
        run: cmake --build "${{ env.CMAKE_BUILD_DIR }}"
      - test: test
        run: ./tests/tests
